// server/prisma/seed/armor.ts

import { PrismaClient, MaterialType, ItemType } from '@prisma/client';
import { fx, seedItemFunction, ItemSeed } from './items';

const seedName: string = 'Armor';

export async function seedArmor(prisma: PrismaClient): Promise<void> {
  await seedItemFunction(prisma, seedName, data);
}

// ---------------------------------------------------------------------------
// SCALING RULES APPLIED
//   toHitBonus  CLOTH  : T0+2  T1+3  T2+5  T3+7  T4+10 T5+13 T6+17 T7+22
//   toHitBonus  LEATHER: T0+1  T1+2  T2+4  T3+6  T4+8  T5+11 T6+15 T7+20
//   toHitBonus  METAL  : T0-1  T1-2  T2-3  T3-4  T4-5  T5-6  T6-7  T7-8
//   toHitBonus  SHIELD : +1 better than METAL peer (lighter load)
//   Slot budget : ARMOR 100% | HELM 60% | GLOVE 40% | BOOT 40% | SHIELD 50%+DR
//   buyPrice    : cost × 1.25  (rounded)
//   sellPrice   : cost × 0.40  (rounded)
//   CLOTH focus : INT, MP, SR, toHit%, dodge
//   LEATHER focus: DEX, dodge, critChance, critDamage
//   METAL focus : STR, CON, HP, DR, critResistance
// ---------------------------------------------------------------------------

const data: ItemSeed[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T0  Starting  (cost 2–4)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'tattered- robe',
    name:         'Tattered Cloth Robe',
    description:  'A threadbare robe barely held together by fraying stitches. Provides almost no protection, but a faint arcane resonance lingers in its weave.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       1.5,
    cost:         2,
    buyPrice:     3,
    sellPrice:    1,
    toHitBonus:   2,
    statEffects:  fx(0, 0, 1, 0,  5, 5,  1, 0,  0, 0, 0,  0, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T1  Basic  (cost 8–20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'novice-cloth-robe',
    name:         'Novice Cloth Robe',
    description:  'Standard-issue attire handed to every new apprentice. Light, unadorned, and faintly imbued with the first lesson of the arcane arts.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       1.8,
    cost:         20,
    buyPrice:     25,
    sellPrice:    8,
    toHitBonus:   3,
    statEffects:  fx(0, 0, 2, 0,  10, 15,  1, 1,  0, 0, 0,  0, 1),
  },
  {
    slug:         'novice-cloth-hood',
    name:         'Novice Cloth Hood',
    description:  'A plain hood sewn from undyed linen. It keeps distractions at bay and channels a spark of magical focus.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.4,
    cost:         12,
    buyPrice:     15,
    sellPrice:    5,
    toHitBonus:   3,
    statEffects:  fx(0, 0, 1, 0,  5, 10,  1, 0,  0, 0, 0,  0, 1),
  },
  {
    slug:         'novice-cloth-glove',
    name:         'Novice Cloth Glove',
    description:  'Thin linen glove that improve the precision of a beginner\'s gestures during incantation.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.CLOTH,
    weight:       0.2,
    cost:         8,
    buyPrice:     10,
    sellPrice:    3,
    toHitBonus:   3,
    statEffects:  fx(0, 0, 1, 0,  0, 8,  1, 0,  0, 0, 0,  0, 0),
  },
  {
    slug:         'novice-cloth-sandals',
    name:         'Novice Cloth Sandals',
    description:  'Soft rope-soled sandals that allow quiet movement. A young mage\'s first footwear of any magical merit.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.CLOTH,
    weight:       0.3,
    cost:         8,
    buyPrice:     10,
    sellPrice:    3,
    toHitBonus:   3,
    statEffects:  fx(0, 1, 0, 0,  0, 8,  0, 1,  0, 0, 0,  0, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T2  Common  (cost 65–120)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'journeyman-robe',
    name:         'Journeyman\'s Robe',
    description:  'Woven from quality cotton threaded with silver inscription-wire. A staple garment for scholars on the road.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       2.0,
    cost:         120,
    buyPrice:     150,
    sellPrice:    48,
    toHitBonus:   5,
    statEffects:  fx(0, 0, 4, 1,  20, 35,  2, 2,  0, 0, 0,  0, 2),
  },
  {
    slug:         'scholar-hood',
    name:         'Scholar\'s Hood',
    description:  'A lined hood embroidered with condensing runes. Sharpens the mind during extended rituals and long study sessions.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.5,
    cost:         80,
    buyPrice:     100,
    sellPrice:    32,
    toHitBonus:   5,
    statEffects:  fx(0, 0, 3, 0,  10, 25,  1, 1,  0, 0, 0,  0, 2),
  },
  {
    slug:         'arcane-cloth-glove',
    name:         'Arcane Cloth Glove',
    description:  'Glove threaded with a fine silver weave that resonates with magical frequencies, sharpening spell accuracy.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.CLOTH,
    weight:       0.25,
    cost:         65,
    buyPrice:     82,
    sellPrice:    26,
    toHitBonus:   5,
    statEffects:  fx(0, 0, 2, 0,  0, 20,  2, 0,  0, 0, 0,  0, 1),
  },
  {
    slug:         'mystic-cloth-sandals',
    name:         'Mystic Cloth Sandals',
    description:  'Sandals strung with runic knot-work that improve magical mobility and offer minor arcane deflection underfoot.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.CLOTH,
    weight:       0.35,
    cost:         65,
    buyPrice:     82,
    sellPrice:    26,
    toHitBonus:   5,
    statEffects:  fx(0, 1, 1, 0,  0, 20,  0, 2,  0, 0, 0,  0, 1),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T3  Uncommon  (cost 550–900)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'mage-battle-robe',
    name:         'Mage\'s Battle Robe',
    description:  'Reinforced with alchemically treated fibers and layered enchantment stitching. Built for the front lines of magical warfare.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       2.5,
    cost:         900,
    buyPrice:     1125,
    sellPrice:    360,
    toHitBonus:   7,
    statEffects:  fx(0, 1, 7, 2,  40, 70,  4, 3,  1, 0, 1,  0, 4),
  },
  {
    slug:         'conjurer-hood',
    name:         'Conjurer\'s Hood',
    description:  'Etched with summoning glyphs along the brim. Deepens the wearer\'s attunement to the ethereal plane.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.6,
    cost:         650,
    buyPrice:     813,
    sellPrice:    260,
    toHitBonus:   7,
    statEffects:  fx(0, 0, 5, 1,  20, 50,  3, 2,  0, 0, 1,  0, 3),
  },
  {
    slug:         'spellweave-glove',
    name:         'Spellweave Glove',
    description:  'Woven from threads spun in a magical forge, these glove amplify casting tempo and sharpened spell impact.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.CLOTH,
    weight:       0.3,
    cost:         550,
    buyPrice:     688,
    sellPrice:    220,
    toHitBonus:   7,
    statEffects:  fx(0, 0, 4, 0,  0, 40,  3, 1,  1, 2, 0,  0, 2),
  },
  {
    slug:         'spellweave-boot',
    name:         'Spellweave Boot',
    description:  'Threaded with levitation runes along the instep. Allow swift repositioning without breaking a spell channel.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.CLOTH,
    weight:       0.4,
    cost:         550,
    buyPrice:     688,
    sellPrice:    220,
    toHitBonus:   7,
    statEffects:  fx(0, 2, 2, 0,  0, 40,  1, 4,  0, 0, 1,  0, 2),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T4  Rare  (cost 3 200–5 500)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'archmage-robes',
    name:         'Archmage\'s Robes',
    description:  'Sewn from mithril-laced silk and enchanted with twelve sub-schools of magic. Donned only by those who have mastered the arcane.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       3.0,
    cost:         5500,
    buyPrice:     6875,
    sellPrice:    2200,
    toHitBonus:   10,
    statEffects:  fx(0, 2, 12, 3,  80, 150,  7, 6,  2, 3, 2,  0, 7),
  },
  {
    slug:         'archmage-cowl',
    name:         'Archmage\'s Cowl',
    description:  'Stitched from the shed skin of astral serpents and lined with condensed stardust. Grants uncanny magical perception.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.7,
    cost:         4000,
    buyPrice:     5000,
    sellPrice:    1600,
    toHitBonus:   10,
    statEffects:  fx(0, 1, 9, 2,  40, 110,  5, 4,  1, 2, 2,  0, 5),
  },
  {
    slug:         'archmage-glove',
    name:         'Archmage\'s Glove',
    description:  'Slender glove that crackle with barely restrained arcane potential. Precision-tailored for complex multi-school spellwork.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.CLOTH,
    weight:       0.35,
    cost:         3200,
    buyPrice:     4000,
    sellPrice:    1280,
    toHitBonus:   10,
    statEffects:  fx(0, 1, 7, 1,  0, 80,  5, 2,  2, 4, 1,  0, 4),
  },
  {
    slug:         'archmage-boot',
    name:         'Archmage\'s Boot',
    description:  'Featherlight boot that leave no sound on any surface. Enchanted to shorten the gap between spell casts.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.CLOTH,
    weight:       0.5,
    cost:         3200,
    buyPrice:     4000,
    sellPrice:    1280,
    toHitBonus:   10,
    statEffects:  fx(0, 3, 4, 1,  0, 80,  2, 7,  1, 1, 2,  0, 3),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T5  Super Rare  (cost 16 000–22 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'celestial-vestments',
    name:         'Celestial Vestments',
    description:  'Woven from captured starlight bound with celestial fiber. Said to have clothed the saints of the ancient Aether Council.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       3.5,
    cost:         22000,
    buyPrice:     27500,
    sellPrice:    8800,
    toHitBonus:   13,
    statEffects:  fx(0, 3, 18, 4,  130, 250,  11, 9,  3, 5, 4,  0, 10),
  },
  {
    slug:         'celestial-cowl',
    name:         'Celestial Cowl',
    description:  'A hood woven from threads of condensed starfire. Those who wear it are said to dream in pure mathematics.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.8,
    cost:         16000,
    buyPrice:     20000,
    sellPrice:    6400,
    toHitBonus:   13,
    statEffects:  fx(0, 2, 13, 3,  65, 180,  8, 7,  2, 4, 3,  0, 8),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T6  Epic  (cost 120 000–180 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'void-robes',
    name:         'Void Robes',
    description:  'Constructed from solidified void-matter harvested at the boundary of reality. Grants dominion over unmaking and creation simultaneously.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       4.0,
    cost:         180000,
    buyPrice:     225000,
    sellPrice:    72000,
    toHitBonus:   17,
    statEffects:  fx(0, 5, 24, 5,  200, 380,  16, 13,  5, 8, 6,  0, 14),
  },
  {
    slug:         'void-cowl',
    name:         'Void Cowl',
    description:  'A hood threaded with anti-matter filaments. Those who peer into the wearer\'s eyes see only an infinite abyss staring back.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.CLOTH,
    weight:       0.9,
    cost:         120000,
    buyPrice:     150000,
    sellPrice:    48000,
    toHitBonus:   17,
    statEffects:  fx(0, 3, 18, 4,  100, 270,  12, 10,  4, 6, 5,  0, 11),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTH ── T7  Legendary  (cost 1 200 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'mythic-astral-robes',
    name:         'Mythic Astral Robes',
    description:  'Transcendent garments said to have draped the shoulders of the very first god of magic. Their origin predates the written word.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.CLOTH,
    weight:       4.5,
    cost:         1200000,
    buyPrice:     1500000,
    sellPrice:    480000,
    toHitBonus:   22,
    statEffects:  fx(0, 8, 30, 7,  320, 500,  22, 18,  8, 12, 9,  0, 15),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T0  Starting  (cost 2–4)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'worn-leather-vest',
    name:         'Worn Leather Vest',
    description:  'A scuffed vest of questionable origin. It smells of old campfire and faint, forgotten adventure.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       3.5,
    cost:         3,
    buyPrice:     4,
    sellPrice:    1,
    toHitBonus:   1,
    statEffects:  fx(0, 1, 0, 0,  8, 0,  0, 1,  0, 0, 0,  1, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T1  Basic  (cost 10–20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'scout-jerkin',
    name:         'Scout\'s Jerkin',
    description:  'A flexible leather vest cut for long-range movement. Preferred by rangers and forward scouts throughout the realm.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       4.0,
    cost:         20,
    buyPrice:     25,
    sellPrice:    8,
    toHitBonus:   2,
    statEffects:  fx(0, 2, 0, 1,  15, 0,  1, 2,  0, 0, 0,  1, 0),
  },
  {
    slug:         'hunter-cap',
    name:         'Hunter\'s Cap',
    description:  'A simple leather cap worn by those who track prey through forest and fen. Keeps rain and twigs out of the eyes.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       0.8,
    cost:         12,
    buyPrice:     15,
    sellPrice:    5,
    toHitBonus:   2,
    statEffects:  fx(0, 1, 0, 0,  8, 0,  1, 1,  0, 0, 0,  0, 0),
  },
  {
    slug:         'ranger-glove',
    name:         'Ranger\'s Glove',
    description:  'Fingerless leather glove offering grip and mobility in equal measure. Essential kit for any wilderness traveler.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.LEATHER,
    weight:       0.4,
    cost:         10,
    buyPrice:     13,
    sellPrice:    4,
    toHitBonus:   2,
    statEffects:  fx(0, 2, 0, 0,  0, 0,  1, 1,  1, 0, 0,  0, 0),
  },
  {
    slug:         'ranger-boot',
    name:         'Ranger\'s Boot',
    description:  'Sturdy trail boot reinforced at the toe and heel. Built for long marches and stealthy approaches through undergrowth.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.LEATHER,
    weight:       1.0,
    cost:         10,
    buyPrice:     13,
    sellPrice:    4,
    toHitBonus:   2,
    statEffects:  fx(0, 2, 0, 0,  0, 0,  0, 2,  0, 0, 0,  1, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T2  Common  (cost 85–150)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'tracker-vest',
    name:         'Tracker\'s Vest',
    description:  'Cured leather stitched with bone needles and treated with herb-oil for flexibility and resilience in all conditions.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       4.5,
    cost:         150,
    buyPrice:     188,
    sellPrice:    60,
    toHitBonus:   4,
    statEffects:  fx(1, 3, 0, 1,  25, 0,  2, 3,  1, 1, 0,  2, 0),
  },
  {
    slug:         'rogue-hood',
    name:         'Rogue\'s Hood',
    description:  'A close-fitting hood that conceals the face and muffles breathing. Standard gear for operatives and assassins in training.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       0.9,
    cost:         100,
    buyPrice:     125,
    sellPrice:    40,
    toHitBonus:   4,
    statEffects:  fx(0, 2, 0, 0,  12, 0,  2, 2,  1, 0, 0,  1, 0),
  },
  {
    slug:         'shadow-glove',
    name:         'Shadow Glove',
    description:  'Black leather glove treated to reduce friction. They improve hand dexterity and blade control under pressure.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.LEATHER,
    weight:       0.45,
    cost:         85,
    buyPrice:     107,
    sellPrice:    34,
    toHitBonus:   4,
    statEffects:  fx(0, 3, 0, 0,  0, 0,  2, 2,  2, 2, 0,  0, 0),
  },
  {
    slug:         'swift-boot',
    name:         'Swift Boot',
    description:  'Lightweight boot with a springed sole layer. Engineered for quick escapes and sudden burst movement.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.LEATHER,
    weight:       1.1,
    cost:         85,
    buyPrice:     107,
    sellPrice:    34,
    toHitBonus:   4,
    statEffects:  fx(0, 3, 0, 0,  0, 0,  1, 4,  0, 0, 0,  1, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T3  Uncommon  (cost 680–1 100)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'assassin-coat',
    name:         'Assassin\'s Coat',
    description:  'A masterwork leather coat treated with shadowbloom extract. Reduces noise, diffuses moonlight, and improves overall lethality.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       5.0,
    cost:         1100,
    buyPrice:     1375,
    sellPrice:    440,
    toHitBonus:   6,
    statEffects:  fx(1, 6, 0, 2,  50, 0,  4, 6,  3, 4, 1,  3, 0),
  },
  {
    slug:         'assassin-mask',
    name:         'Assassin\'s Mask',
    description:  'A sculpted bone-and-leather mask that enhances peripheral vision and muffles breathing. Terror is woven into its design.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       1.0,
    cost:         800,
    buyPrice:     1000,
    sellPrice:    320,
    toHitBonus:   6,
    statEffects:  fx(0, 4, 0, 1,  25, 0,  3, 4,  2, 3, 1,  2, 0),
  },
  {
    slug:         'venomweave-glove',
    name:         'Venomweave Glove',
    description:  'Lined with venomthorn fiber pressed into the inner lining. Strikes with these equipped leave a lingering, burning sensation.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.LEATHER,
    weight:       0.5,
    cost:         680,
    buyPrice:     850,
    sellPrice:    272,
    toHitBonus:   6,
    statEffects:  fx(0, 4, 0, 0,  0, 0,  3, 3,  3, 5, 0,  1, 0),
  },
  {
    slug:         'shadowstep-boot',
    name:         'Shadowstep Boot',
    description:  'Inscribed with shadow-runes along the sole. Each footfall leaves no trace on soft earth or snow.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.LEATHER,
    weight:       1.2,
    cost:         680,
    buyPrice:     850,
    sellPrice:    272,
    toHitBonus:   6,
    statEffects:  fx(0, 5, 0, 0,  0, 0,  2, 7,  1, 2, 0,  1, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T4  Rare  (cost 3 400–6 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'darkwood-leather-coat',
    name:         'Darkwood Leather Coat',
    description:  'Hardened leather overlaid with darkwood splints and shadow-fiber stitching. Rare, expertly crafted, and whisper-quiet.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       6.0,
    cost:         6000,
    buyPrice:     7500,
    sellPrice:    2400,
    toHitBonus:   8,
    statEffects:  fx(2, 10, 0, 3,  90, 0,  7, 10,  5, 7, 2,  5, 0),
  },
  {
    slug:         'darkwood-ranger-hood',
    name:         'Darkwood Ranger Hood',
    description:  'A reinforced hood crafted from darkwood-treated hides. Offers protection that rivals light plate armor — without the noise.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       1.3,
    cost:         4200,
    buyPrice:     5250,
    sellPrice:    1680,
    toHitBonus:   8,
    statEffects:  fx(1, 7, 0, 2,  45, 0,  5, 7,  3, 5, 2,  3, 0),
  },
  {
    slug:         'darkwood-shadow-glove',
    name:         'Darkwood Shadow Glove',
    description:  'Shadow glove reinforced with darkwood knuckle-guards. Increase strike precision and raw damage output significantly.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.LEATHER,
    weight:       0.6,
    cost:         3400,
    buyPrice:     4250,
    sellPrice:    1360,
    toHitBonus:   8,
    statEffects:  fx(1, 7, 0, 0,  0, 0,  5, 4,  4, 7, 1,  2, 0),
  },
  {
    slug:         'darkwood-shadowstep-boot',
    name:         'Darkwood Shadowstep Boot',
    description:  'Shadow boot with darkwood-layered soles. Superior grip and near-silent movement across any terrain type.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.LEATHER,
    weight:       1.5,
    cost:         3400,
    buyPrice:     4250,
    sellPrice:    1360,
    toHitBonus:   8,
    statEffects:  fx(1, 8, 0, 1,  0, 0,  3, 11,  2, 3, 1,  2, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T5  Super Rare  (cost 20 000–28 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'void-stalker-coat',
    name:         'Void Stalker\'s Coat',
    description:  'Woven from void-fiber stripped from creatures at the boundary of existence itself. The wearer becomes nearly imperceptible to all senses.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       7.0,
    cost:         28000,
    buyPrice:     35000,
    sellPrice:    11200,
    toHitBonus:   11,
    statEffects:  fx(3, 16, 0, 4,  140, 0,  11, 17,  8, 11, 4,  7, 0),
  },
  {
    slug:         'void-stalker-mask',
    name:         'Void Stalker\'s Mask',
    description:  'A mask that distorts the wearer\'s silhouette at the edges. Enemies struggle to acquire a targeting lock on those who wear it.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       1.5,
    cost:         20000,
    buyPrice:     25000,
    sellPrice:    8000,
    toHitBonus:   11,
    statEffects:  fx(2, 12, 0, 3,  70, 0,  8, 13,  6, 8, 3,  5, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEATHER ── T6  Epic  (cost 150 000–220 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'infernal-leather-vestment',
    name:         'Infernal Leather Vestment',
    description:  'Flayed from the hide of a defeated pit lord and cured in concentrated hellfire. Burns with an inner light that dims nearby torches.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.LEATHER,
    weight:       8.0,
    cost:         220000,
    buyPrice:     275000,
    sellPrice:    88000,
    toHitBonus:   15,
    statEffects:  fx(5, 22, 0, 6,  220, 0,  16, 22,  12, 15, 6,  10, 0),
  },
  {
    slug:         'infernal-leather-mask',
    name:         'Infernal Leather Mask',
    description:  'Hellfire-cured hide etched with infernal runes on every surface. The gaze of its wearer carries a palpable, physical menace.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.LEATHER,
    weight:       1.7,
    cost:         150000,
    buyPrice:     187500,
    sellPrice:    60000,
    toHitBonus:   15,
    statEffects:  fx(3, 16, 0, 4,  110, 0,  12, 17,  9, 11, 5,  7, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T0  Starting  (cost 2–4)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'rusty-iron-vest',
    name:         'Rusty Iron Vest',
    description:  'A battered vest of corroded iron plates. Barely functional, but in a pinch it is better than bare skin.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       10.0,
    cost:         4,
    buyPrice:     5,
    sellPrice:    2,
    toHitBonus:   -1,
    statEffects:  fx(1, 0, 0, 1,  12, 0,  0, 0,  0, 0, 0,  2, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T1  Basic  (cost 12–35)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'iron-breastplate',
    name:         'Iron Breastplate',
    description:  'A solid iron breastplate hammered out in a village forge. No frills, no enchantments — just dependable protection.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       12.0,
    cost:         35,
    buyPrice:     44,
    sellPrice:    14,
    toHitBonus:   -2,
    statEffects:  fx(2, 0, 0, 2,  25, 0,  0, 0,  0, 0, 1,  3, 0),
  },
  {
    slug:         'iron-helm',
    name:         'Iron Helm',
    description:  'A basic iron helm that protects the skull without decoration or enchantment. Reliable, affordable, and unglamorous.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       3.0,
    cost:         22,
    buyPrice:     28,
    sellPrice:    9,
    toHitBonus:   -2,
    statEffects:  fx(1, 0, 0, 1,  12, 0,  0, 0,  0, 0, 1,  2, 0),
  },
  {
    slug:         'iron-gauntlets',
    name:         'Iron Gauntlets',
    description:  'Articulated iron gauntlets protecting hands and forearms. Standard combat gear issued to new recruits across every kingdom.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.METAL,
    weight:       1.5,
    cost:         18,
    buyPrice:     23,
    sellPrice:    7,
    toHitBonus:   -2,
    statEffects:  fx(2, 0, 0, 0,  0, 0,  0, 0,  0, 0, 0,  2, 0),
  },
  {
    slug:         'iron-sabatons',
    name:         'Iron Sabatons',
    description:  'Heavy iron foot-armor covering toe to shin. Slow and clunky, but a dependable foundation for any armored fighter.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.METAL,
    weight:       2.0,
    cost:         18,
    buyPrice:     23,
    sellPrice:    7,
    toHitBonus:   -2,
    statEffects:  fx(1, 0, 0, 1,  0, 0,  0, 0,  0, 0, 1,  2, 0),
  },
  {
    slug:         'wooden-shield',
    name:         'Wooden Shield',
    description:  'A round wooden shield banded with iron at the rim. Common among militias, town guards, and anyone on a tight budget.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       3.5,
    cost:         12,
    buyPrice:     15,
    sellPrice:    5,
    toHitBonus:   -1,
    statEffects:  fx(0, 0, 0, 1,  10, 0,  0, 1,  0, 0, 2,  3, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T2  Common  (cost 90–200)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'steel-breastplate',
    name:         'Steel Breastplate',
    description:  'A well-tempered steel breastplate with a polished finish. Standard armor for professional soldiers and city guard captains.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       13.0,
    cost:         200,
    buyPrice:     250,
    sellPrice:    80,
    toHitBonus:   -3,
    statEffects:  fx(3, 0, 0, 3,  45, 0,  0, 0,  0, 0, 2,  5, 0),
  },
  {
    slug:         'steel-helm',
    name:         'Steel Helm',
    description:  'A full-coverage steel helm with a fixed visor. Offers superior head protection compared to its iron predecessor.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       3.5,
    cost:         130,
    buyPrice:     163,
    sellPrice:    52,
    toHitBonus:   -3,
    statEffects:  fx(2, 0, 0, 2,  22, 0,  0, 0,  0, 0, 2,  3, 0),
  },
  {
    slug:         'steel-gauntlets',
    name:         'Steel Gauntlets',
    description:  'Articulated steel gauntlets with reinforced knuckle-plates. Favored by knights and heavy infantry throughout the realm.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.METAL,
    weight:       1.8,
    cost:         110,
    buyPrice:     138,
    sellPrice:    44,
    toHitBonus:   -3,
    statEffects:  fx(3, 0, 0, 0,  0, 0,  0, 0,  0, 0, 1,  3, 0),
  },
  {
    slug:         'steel-sabatons',
    name:         'Steel Sabatons',
    description:  'Articulated steel foot-armor allowing limited ankle articulation. A notable improvement over the rigid iron equivalent.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.METAL,
    weight:       2.5,
    cost:         110,
    buyPrice:     138,
    sellPrice:    44,
    toHitBonus:   -3,
    statEffects:  fx(2, 0, 0, 1,  0, 0,  0, 0,  0, 0, 2,  3, 0),
  },
  {
    slug:         'iron-kite-shield',
    name:         'Iron Kite Shield',
    description:  'A kite-shaped iron shield providing coverage from shoulder to mid-thigh. Popular with mounted cavalry and heavy-line fighters.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       5.0,
    cost:         90,
    buyPrice:     113,
    sellPrice:    36,
    toHitBonus:   -2,
    statEffects:  fx(0, 0, 0, 2,  20, 0,  0, 1,  0, 0, 3,  5, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T3  Uncommon  (cost 650–1 400)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'knight-breastplate',
    name:         'Knight\'s Breastplate',
    description:  'A masterwork steel breastplate bearing engraved heraldic motifs. Marks its wearer as a warrior of recognized noble standing.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       14.5,
    cost:         1400,
    buyPrice:     1750,
    sellPrice:    560,
    toHitBonus:   -4,
    statEffects:  fx(5, 0, 0, 5,  80, 0,  0, 0,  0, 0, 3,  7, 0),
  },
  {
    slug:         'knight-helm',
    name:         'Knight\'s Helm',
    description:  'A great helm with a decorated faceplate and thick padded interior. Commands respect across the battlefield from both allies and enemies.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       4.5,
    cost:         950,
    buyPrice:     1188,
    sellPrice:    380,
    toHitBonus:   -4,
    statEffects:  fx(3, 0, 0, 3,  40, 0,  0, 0,  0, 0, 3,  5, 0),
  },
  {
    slug:         'knight-gauntlets',
    name:         'Knight\'s Gauntlets',
    description:  'Full-plate gauntlets with articulated finger sections. Allows surprising mobility for their substantial weight class.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.METAL,
    weight:       2.2,
    cost:         750,
    buyPrice:     938,
    sellPrice:    300,
    toHitBonus:   -4,
    statEffects:  fx(4, 0, 0, 1,  0, 0,  0, 0,  0, 0, 2,  5, 0),
  },
  {
    slug:         'knight-sabatons',
    name:         'Knight\'s Sabatons',
    description:  'Full sabatons built from overlapping articulated plates. Their clicking footfall announces the wearer\'s presence from around corners.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.METAL,
    weight:       3.0,
    cost:         750,
    buyPrice:     938,
    sellPrice:    300,
    toHitBonus:   -4,
    statEffects:  fx(3, 0, 0, 2,  0, 0,  0, 0,  0, 0, 3,  5, 0),
  },
  {
    slug:         'steel-tower-shield',
    name:         'Steel Tower Shield',
    description:  'A full-body steel tower shield that doubles as mobile cover. It slows movement considerably but grants exceptional protection.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       8.0,
    cost:         650,
    buyPrice:     813,
    sellPrice:    260,
    toHitBonus:   -3,
    statEffects:  fx(0, 0, 0, 3,  35, 0,  0, 2,  0, 0, 5,  8, 0),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T4  Rare  (cost 3 800–7 500)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'mithril-breastplate',
    name:         'Mithril Breastplate',
    description:  'Forged from the legendary silver-metal of the deep mountains. Lighter than iron yet stronger than any tempered steel.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       10.0,
    cost:         7500,
    buyPrice:     9375,
    sellPrice:    3000,
    toHitBonus:   -5,
    statEffects:  fx(8, 1, 0, 7,  150, 0,  1, 1,  0, 0, 5,  10, 2),
  },
  {
    slug:         'mithril-helm',
    name:         'Mithril Helm',
    description:  'A sculpted mithril helm that catches light like living silver fire. Beautiful in court and battle-hardened on the field.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       2.8,
    cost:         5000,
    buyPrice:     6250,
    sellPrice:    2000,
    toHitBonus:   -5,
    statEffects:  fx(5, 0, 0, 5,  75, 0,  0, 1,  0, 0, 5,  7, 2),
  },
  {
    slug:         'mithril-gauntlets',
    name:         'Mithril Gauntlets',
    description:  'Lightweight gauntlets of pure mithril that flex naturally with the hand. They deflect heavy blows while barely slowing the wearer.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.METAL,
    weight:       1.2,
    cost:         3800,
    buyPrice:     4750,
    sellPrice:    1520,
    toHitBonus:   -5,
    statEffects:  fx(6, 1, 0, 2,  0, 0,  0, 0,  0, 0, 3,  7, 1),
  },
  {
    slug:         'mithril-sabatons',
    name:         'Mithril Sabatons',
    description:  'Foot armor of pure mithril that is lighter than iron yet tougher than steel. Allows a more natural fighting stance than any comparable metal.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.METAL,
    weight:       1.8,
    cost:         3800,
    buyPrice:     4750,
    sellPrice:    1520,
    toHitBonus:   -5,
    statEffects:  fx(5, 1, 0, 3,  0, 0,  0, 1,  0, 0, 4,  7, 1),
  },
  {
    slug:         'mithril-shield',
    name:         'Mithril Shield',
    description:  'A mithril heater shield inscribed with protective ward-runes along its inner face. Light enough to feel like an extension of the arm.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       5.5,
    cost:         4500,
    buyPrice:     5625,
    sellPrice:    1800,
    toHitBonus:   -4,
    statEffects:  fx(0, 1, 0, 4,  60, 0,  1, 3,  0, 0, 7,  11, 3),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T5  Super Rare  (cost 22 000–35 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'adamantine-breastplate',
    name:         'Adamantine Breastplate',
    description:  'Smelted from the rarest ore in the known world. This breastplate has reportedly turned aside dragon claws and direct arcane bombardment.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       12.0,
    cost:         35000,
    buyPrice:     43750,
    sellPrice:    14000,
    toHitBonus:   -6,
    statEffects:  fx(14, 1, 0, 12,  250, 0,  1, 1,  0, 0, 8,  14, 5),
  },
  {
    slug:         'adamantine-helm',
    name:         'Adamantine Helm',
    description:  'A seamless dome of adamantine with a narrow vision slit. Near-indestructible, and greatly feared by enemy spellcasters.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       3.8,
    cost:         24000,
    buyPrice:     30000,
    sellPrice:    9600,
    toHitBonus:   -6,
    statEffects:  fx(9, 0, 0, 8,  125, 0,  0, 0,  0, 0, 8,  10, 5),
  },
  {
    slug:         'adamantine-shield',
    name:         'Adamantine Shield',
    description:  'A near-indestructible round shield of adamantine. Warriors positioned behind it are regarded as virtually immovable objects.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       7.5,
    cost:         22000,
    buyPrice:     27500,
    sellPrice:    8800,
    toHitBonus:   -5,
    statEffects:  fx(0, 1, 0, 7,  100, 0,  1, 4,  0, 0, 11,  15, 6),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T6  Epic  (cost 160 000–280 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'celestial-plate',
    name:         'Celestial Plate',
    description:  'Forged at the core of a dying star by divine smiths. Its surface shimmers with barely contained holy energy that scorches the faithless.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       14.0,
    cost:         280000,
    buyPrice:     350000,
    sellPrice:    112000,
    toHitBonus:   -7,
    statEffects:  fx(20, 2, 3, 18,  380, 80,  2, 2,  1, 2, 11,  15, 10),
  },
  {
    slug:         'celestial-helm',
    name:         'Celestial Helm',
    description:  'A helm that radiates a calm golden light. Wearing it brings clarity of thought even at the height of furious battle.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       4.5,
    cost:         180000,
    buyPrice:     225000,
    sellPrice:    72000,
    toHitBonus:   -7,
    statEffects:  fx(13, 1, 2, 12,  190, 60,  1, 1,  0, 1, 10,  11, 8),
  },
  {
    slug:         'celestial-shield',
    name:         'Celestial Shield',
    description:  'A blazing shield of divine alloy. Its face deflects not only physical strikes but curses, void-fire, and raw entropy.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       9.0,
    cost:         160000,
    buyPrice:     200000,
    sellPrice:    64000,
    toHitBonus:   -6,
    statEffects:  fx(0, 2, 3, 10,  150, 60,  2, 5,  0, 0, 14,  15, 13),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // METAL ── T7  Legendary  (cost 1 600 000–2 500 000)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    slug:         'mythic-dragon-plate',
    name:         'Mythic Dragon Plate',
    description:  'Hammered from the scales of the first and mightiest dragon ever to have drawn breath. Its mere presence makes the earth tremble underfoot.',
    itemType:     ItemType.ARMOR,
    materialType: MaterialType.METAL,
    weight:       18.0,
    cost:         2500000,
    buyPrice:     3125000,
    sellPrice:    1000000,
    toHitBonus:   -8,
    statEffects:  fx(30, 3, 5, 25,  500, 120,  3, 3,  2, 4, 14,  15, 15),
  },
  {
    slug:         'mythic-dragon-helm',
    name:         'Mythic Dragon Helm',
    description:  'Carved from a great dragon\'s skull-cap. Ancient runes inscribed inside grant the wearer the legendary resilience of the beast itself.',
    itemType:     ItemType.HAT,
    materialType: MaterialType.METAL,
    weight:       6.0,
    cost:         1800000,
    buyPrice:     2250000,
    sellPrice:    720000,
    toHitBonus:   -8,
    statEffects:  fx(20, 2, 3, 17,  280, 80,  2, 2,  1, 3, 12,  13, 13),
  },
  {
    slug:         'mythic-dragon-gauntlets',
    name:         'Mythic Dragon Gauntlets',
    description:  'Gauntlets shaped from the knuckle-plates of the eldest dragon. Each strike from them is said to echo like a thunderclap across the battlefield.',
    itemType:     ItemType.GLOVE,
    materialType: MaterialType.METAL,
    weight:       4.0,
    cost:         1600000,
    buyPrice:     2000000,
    sellPrice:    640000,
    toHitBonus:   -8,
    statEffects:  fx(22, 2, 2, 14,  0, 0,  2, 1,  2, 5, 10,  13, 12),
  },
  {
    slug:         'mythic-dragon-sabatons',
    name:         'Mythic Dragon Sabatons',
    description:  'Foot armor fashioned from the clawed toes of a world-serpent dragon. The ground cracks faintly beneath every step.',
    itemType:     ItemType.BOOT,
    materialType: MaterialType.METAL,
    weight:       5.0,
    cost:         1600000,
    buyPrice:     2000000,
    sellPrice:    640000,
    toHitBonus:   -8,
    statEffects:  fx(18, 2, 2, 16,  0, 0,  1, 2,  1, 3, 11,  13, 12),
  },
  {
    slug:         'mythic-dragon-shield',
    name:         'Mythic Dragon Shield',
    description:  'A shield carved from a single dragon wing-bone and faced with smelted fang-metal. An artifact of unparalleled endurance and mythic standing.',
    itemType:     ItemType.SHIELD,
    materialType: MaterialType.METAL,
    weight:       12.0,
    cost:         1600000,
    buyPrice:     2000000,
    sellPrice:    640000,
    toHitBonus:   -7,
    statEffects:  fx(0, 2, 4, 15,  220, 80,  2, 6,  1, 2, 15,  15, 15),
  },

];
