name: Prisma Migrations

on:
  pull_request:
    paths:
      - "../../server/prisma"
      - "../../server/package.json"
      - "../../server/package-lock.json"

jobs:
  prisma-validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Prisma validate
        run: npx prisma validate

      - name: Prisma migrate diff (sanity check)
        run: npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --exit-code
